### ISSUE TITLE
multiple send is not working correctly.

### ISSUE THREAD

**Issue by bluesven869** [arthurkushman/php-wss#47]
$config = new ClientConfig();
        $config->setTimeout(10);
        $config->setFragmentSize(406400);
        $client = new WebSocketClient( getenv('WEBSOCKET_ENDPOINT') , $config );
        $client->send("THISISDATA1");
        $client->send("THISISDATA2");
        $client->send("THISISDATA3");
        $client->send("THISISDATA4");

3rd message,  4th message does not send to server.

Do you have any idea?

**Comment by arthurkushman** [comment]
Hi, sorry can't be out here for some time because have been busy.
Tried to rewrite my tests with something like this and got no error, there are also another tests have been executed successfully:
```php
        $recvMsg = '{"user_id" : 123}';
        $client = new WebSocketClient($this->url, new ClientConfig());
        try {
            $client->send($recvMsg);
            $client->send($recvMsg);
            $client->send($recvMsg);
            $client->send($recvMsg);
            $client->send($recvMsg);
        } catch (BadOpcodeException $e) {
            echo 'Couldn`t sent: ' . $e->getMessage();
        }
        $recv = $client->receive();
        $this->assertEquals($recv, $recvMsg);
```
The overall result of tests:
```
phpunit --bootstrap ./tests/_bootstrap.php ./tests/WebSocketClientTest.php
PHPUnit 7.1.5 by Sebastian Bergmann and contributors.

...                                                                 3 / 3 (100%)

Time: 76 ms, Memory: 10.00MB

OK (3 tests, 3 assertions)
```

**Comment by aln-1** [comment]
Hi,
Sorry to jump in but I was looking to do multiple streams ws client and I came across your library (not wanting to write everything myself, your code looks decent enough).
The multi-send example above will not work. You MUST read from the socket after sending.
What I'm missing here is the possibility to use stream_select for the client.
Since you made the $socket parameter private this also can not be done without overwriting your library.
If you'll make the $socket protected or put a getter then one could get the socket and use it in stream_select to achieve multi-stream client.

**Comment by arthurkushman** [comment]
Hello, just to clarify - you want to get an access to the main socket resource to be able to make with it whatever u need as a consumer of a library? This is not what should be in any library strategy/architecture. Let me show u a couple examples here: 
- u write any unframed/corrupted data into socket resource and it's behaviour in context of library is unpredictable
- u change the timeout of socket resource - behaviour unpredictable 
etc there can be more examples on this approach.

On the other hand, we can expand functionality to fit your needs, could u post some examples of a particular usage with `stream_select` here?

**Comment by aln-1** [comment]
@arthurkushman who are you writing a library for if not for code developers? So please let them expend the library the way the see fit. And if someone says he has a problem extending your classes then probably you should reconsider your data visibility scopes.
Anyway... WS has different uses, how about multi-threaded file transfer as a use case?

**Comment by arthurkushman** [comment]
@aln-1 I've already has been written about the problems that can occur with main client socket `resource` and offered you to propose the solution how u see it would be more relatively implemented into the library to let all developers do what they want to do with say `stream_select` , my proposition would be something like this:
```php
$client = new WebSocketClient(...);
$client->runOnSelect(function($opts) {
  // junior-developer code
  // middle-developer code
  // senior-developer code
  
  // do other stuff in context of stream_select execution
});
```

What do u mean by multi-threaded file transfer, can u give an example?

**Comment by aln-1** [comment]
You don't get it :)
Never mind, thank you for your time.

**Comment by arthurkushman** [comment]
Ok, your shots was 1st and 2nd, mine is 3d - you are not only understand the whole concept of library, that is why your decision of making property `$socket` protected (either making it accessible via getter) is totally wrong because of immutability and SOLID context, but also You make a lot of trivial mistakes in English, which is for me seems that people who want to offend others definitely can not afford them-selfs.

Good luck. 

PS This issue is closed because of misunderstanding of concepts/architecture features, also an inability of participants to provide any examples nor adequate proposals.
